# By default, SwiftLint uses a set of sensible default rules you can adjust:
disabled_rules: # rule identifiers turned on by default to exclude from running
  - colon
  - comma
  - control_statement
  - line_length

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
