# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProjetoFinal' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.7.0'
  pod 'AlamofireImage', '~> 3.4.0'
  pod 'Commons' , :git=>'https://github.com/Lleitao1/Commons.git', :branch=>'main'
  pod 'detalhesBit' , :git=>'https://github.com/mathiasnonohay/moduloDetalhesBit.git', :branch=>'develop'

  # Pods for ProjetoFinal

  target 'ProjetoFinalTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProjetoFinalUITests' do
    # Pods for testing
  end

end
